language: android
jdk: oraclejdk7
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-19
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-19
sudo: required
before_install:
  - chmod +x travis/before_install.sh
  - ./travis/before_install.sh
before_script:
  - mksdcard -l mySdCard 64M mySdCard.img
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -sdcard mySdCard.img &
script:
  - ./gradlew build
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - adb logcat *:I | grep "jni/" &
  - adb logcat *:I > logcat.log &
  - ./gradlew connectedAndroidTest
after_failure:
  - ./android-ndk-r10e/ndk-stack -sym tests/obj/local/armeabi-v7a -dump logcat.log
