 /* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "time.h"
/* Header for class com_example_frameworktest_NativeTime */

#ifndef _Included_com_VRSeen_sensor_NativeTime
#define _Included_com_VRSeen_sensor_NativeTime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_frameworktest_NativeTime
 * Method:    getCurrentTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_VRSeen_sensor_NativeTime_getCurrentTime
  (JNIEnv *, jclass);

static long long getCurrentTime() {
    timespec ts;
    clock_gettime(CLOCK_REALTIME, &ts); // Works on Linux
    long long time = static_cast<long long>(ts.tv_sec)
            * static_cast<long long>(1000000000)
            + static_cast<long long>(ts.tv_nsec);
    return time;
}

#ifdef __cplusplus
}
#endif
#endif












