/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_frameworktest_NativeUSensor */

#ifndef _Included_com_VRSeen_sensor_NativeUSensor
#define _Included_com_VRSeen_sensor_NativeUSensor
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_example_frameworktest_NativeUSensor
 * Method:    ctor
 * Signature: ()J
 */

JNIEXPORT jlong JNICALL Java_com_vrseen_sensor_NativeUSensor_ctor
  (JNIEnv *, jclass);

/*
 * Class:     com_example_frameworktest_NativeUSensor
 * Method:    update
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_vrseen_sensor_NativeUSensor_update
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     com_example_frameworktest_NativeUSensor
 * Method:    getTimeStamp
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_vrseen_sensor_NativeUSensor_getTimeStamp
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_frameworktest_NativeUSensor
 * Method:    getData
 * Signature: (J)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_vrseen_sensor_NativeUSensor_getData
  (JNIEnv *, jclass, jlong);


#ifdef __cplusplus
}
#endif
#endif
